### ISSUE TITLE
Feature list / requirements for v0.1.0 release

### ISSUE THREAD

**Issue by trappitsch** [trappitsch/box#27]
Here's a todo list of features that should be available for an initial `v0.1.0` release:

- [x] Fix issues when using local `pyapp` source #29 
- [x] Let user select the PyApp version that should be downloaded and used #34 
- [x] Better test coverage #35 
- [x] At least one example/demonstration on how to use `box` in the docs
- [x] GUI support - requires PyApp to better support GUI's (https://github.com/ofek/pyapp/issues/96). #28 
- [x] Section in the docs stating that breaking changes might occure
- [x] Start a changelog with initial release notes

As more things come to mind, I will edit this post and add/remove/elaborate. Please add comments below if you want to have additional features!

**Note**: This should only be a bare-bones list of capabilities that I would like to have. Further enhancements will be in a separate issue and will, once out there, come with increased version numbering.
